# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import collections.abc
import numpy
import numpy.typing
import typing
__all__ = [
    "Capabilities",
    "Device",
    "DeviceBusy",
    "DeviceNotFound",
    "MediaError",
    "ScanCancelled",
    "ScanResult",
    "ScannerError",
    "Session",
    "TransientError",
    "TransportError",
    "UnsupportedError",
    "list_devices",
]

@typing.final
class Capabilities:
    r"""
    What a scanner can do, for the model and the adapter it has loaded
    
    A flat view of `nkscan::capability::Capabilities`. The Rust side carries richer enums; this
    projects them into plain values, since that is what reads well from Python.
    """
    @property
    def model(self) -> builtins.str: ...
    @property
    def adapter(self) -> builtins.str:
        r"""
        The loaded adapter's part number, or a description where the part is not pinned down
        """
    @property
    def dpi(self) -> builtins.list[builtins.int]: ...
    @property
    def optical_dpi(self) -> builtins.int:
        r"""
        The sensor's own pitch, which is not 4000 on every model
        """
    @property
    def depth(self) -> builtins.int:
        r"""
        Bits per sample the converter resolves; the wire is always 16 wide
        """
    @property
    def multisample(self) -> builtins.list[builtins.int]: ...
    @property
    def ir_channel(self) -> builtins.bool: ...
    @property
    def kodachrome_ice(self) -> builtins.bool: ...
    @property
    def max_area_mm(self) -> tuple[builtins.float, builtins.float]: ...
    @property
    def auto_exposure(self) -> builtins.bool:
        r"""
        Whether the host meters, which is also what makes a white balance lock possible
        """
    @property
    def lock_white_balance(self) -> builtins.bool: ...
    @property
    def single_line(self) -> builtins.bool: ...
    @property
    def eject(self) -> builtins.str:
        r"""
        What ejecting does here: `none`, `holder`, `film`, `rewind` or `feed_next`
        """
    @property
    def can_eject(self) -> builtins.bool: ...
    @property
    def overview(self) -> builtins.bool:
        r"""
        Whether this adapter has a thumbnail pass
        """
    @property
    def frames(self) -> typing.Optional[builtins.int]:
        r"""
        How many frames the adapter presents, where that is a fixed property of it
        """
    @property
    def detects_frames(self) -> builtins.bool:
        r"""
        Whether the frames have to be found rather than being mechanically fixed
        """
    @property
    def senses_frames(self) -> builtins.bool:
        r"""
        Whether the transport senses the frames and reports a table
        """
    @property
    def batch(self) -> builtins.bool: ...
    @property
    def strip_offset(self) -> builtins.bool: ...
    @property
    def focus_range(self) -> typing.Optional[tuple[builtins.int, builtins.int]]: ...

@typing.final
class Device:
    r"""
    A scanner the search found, not yet opened
    """
    @property
    def id(self) -> builtins.str: ...
    @property
    def vendor(self) -> builtins.str: ...
    @property
    def model(self) -> builtins.str: ...
    @property
    def capabilities(self) -> Capabilities: ...

class DeviceBusy(TransientError):
    r"""
    Something else holds it.
    """
    ...

class DeviceNotFound(ScannerError):
    r"""
    No such scanner.
    """
    ...

class MediaError(ScannerError):
    r"""
    No film, or nothing recognizable on it. Retrying will not help.
    """
    ...

class ScanCancelled(ScannerError):
    r"""
    The pass was stopped.
    """
    ...

@typing.final
class ScanResult:
    r"""
    One frame, as it came off the scanner
    
    Linear 16-bit ADC counts, not display-referred: applying a transfer curve is the caller's.
    """
    @property
    def rgb(self) -> numpy.typing.NDArray[numpy.uint16]:
        r"""
        (height, width, 3) uint16
        """
    @property
    def ir(self) -> typing.Optional[numpy.typing.NDArray[numpy.uint16]]:
        r"""
        (height, width) uint16, or None when infrared was not captured
        """
    @property
    def dpi(self) -> builtins.int: ...
    @property
    def device_model(self) -> builtins.str: ...
    @property
    def frame(self) -> builtins.int: ...

class ScannerError(builtins.RuntimeError):
    r"""
    Any scanner failure.
    """
    ...

@typing.final
class Session:
    r"""
    An exclusive hold on one scanner
    """
    @property
    def device_id(self) -> builtins.str: ...
    @property
    def model(self) -> builtins.str: ...
    @property
    def capabilities(self) -> Capabilities:
        r"""
        What this unit reports, which is more accurate than what `list_devices` could say
        """
    @property
    def gain(self) -> tuple[builtins.int, builtins.int, builtins.int, builtins.int]:
        r"""
        The gain the next pass will use, as `(red, green, blue, ir)`
        """
    def __new__(cls, device_id: builtins.str) -> Session:
        r"""
        Claim the scanner `device_id` names, as `list_devices` reported it
        """
    def media_loaded(self) -> builtins.bool:
        r"""
        Whether there is film in the scanner now
        """
    def sensed_frames(self) -> typing.Optional[builtins.int]:
        r"""
        How many frames the loaded holder reports, `None` where the model cannot be asked
        
        A vendor page read rather than a pass, so it answers before the mechanism moves — and on
        the models that clear it as the film advances, before the first pass is the only time it
        means anything. `0` is an empty transport, which is not the same answer as `None`.
        """
    def prepare(self, *, frames: typing.Optional[builtins.int] = None, detect: builtins.bool = False, pitch_mm: typing.Optional[builtins.float] = None, offset_mm: builtins.float = 0.0, offsets_mm: typing.Optional[typing.Sequence[builtins.float]] = None, gain: typing.Optional[typing.Sequence[builtins.int]] = None, lock_white_balance: builtins.bool = False, wait_for_media_s: builtins.float = 300.0, progress: collections.abc.Callable[[int, int], bool | None] | None = None) -> builtins.int:
        r"""
        Wake the mechanism, settle the exposure and place the frames, returning how many
        
        `detect` asks the scanner to find them with an overview pass, where it can. Otherwise they
        are placed at `pitch_mm`, or at whatever the loaded holder reports. `gain` as a 3- or
        4-tuple holds the exposure and skips metering.
        
        `offsets_mm` shifts each frame along the feed, the last value repeating down the strip, and
        takes the place of `offset_mm` when both are given.
        """
    def scan(self, index: builtins.int = 0, *, dpi: builtins.int = 4000, ir: builtins.bool = False, focus: builtins.str = 'auto', multisample: builtins.int = 1, single_line: builtins.bool = False, window: typing.Optional[tuple[builtins.float, builtins.float, builtins.float, builtins.float]] = None, progress: collections.abc.Callable[[int, int], bool | None] | None = None) -> ScanResult:
        r"""
        Focus, expose and scan one of the placed frames
        """
    def overview(self, *, progress: collections.abc.Callable[[int, int], bool | None] | None = None) -> ScanResult:
        r"""
        The whole strip in one low-resolution pass, as Nikon Scan's thumbnail view
        
        What a host needs to show the film and let someone pick or place frames on it. `prepare`
        with `detect=True` runs the same pass and finds the frames itself; this hands back the
        image instead. `dpi` on the result is the pass's own, which is what maps a point on the
        thumbnail back to a position on the film.
        """
    def lock_gain(self) -> None:
        r"""
        Hold whatever gain the last scan settled on, so the rest of the roll matches it
        """
    def eject(self) -> builtins.str:
        r"""
        Send the film back out
        """
    def abort(self) -> None:
        r"""
        Throw away a pass nobody is going to read, so the session stays usable
        """
    def close(self) -> None:
        r"""
        Release the scanner. Idempotent, and using the session afterwards raises.
        """
    def __enter__(self) -> Session: ...
    def __exit__(self, _type: typing.Optional[typing.Any], _value: typing.Optional[typing.Any], _traceback: typing.Optional[typing.Any]) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class TransientError(ScannerError):
    r"""
    A failure worth retrying: a link glitch, a busy device, a short read.
    """
    ...

class TransportError(TransientError):
    r"""
    The link faltered.
    """
    ...

class UnsupportedError(ScannerError):
    r"""
    This scanner does not have that setting.
    """
    ...

def list_devices() -> builtins.list[Device]:
    r"""
    Every scanner attached that this library can drive
    
    Asks each device who it is and nothing more, so it is safe to call while another process holds
    one.
    """

