/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sg_io_hdr {
    pub interface_id: ::std::os::raw::c_int,
    pub dxfer_direction: ::std::os::raw::c_int,
    pub cmd_len: ::std::os::raw::c_uchar,
    pub mx_sb_len: ::std::os::raw::c_uchar,
    pub iovec_count: ::std::os::raw::c_ushort,
    pub dxfer_len: ::std::os::raw::c_uint,
    pub dxferp: *mut ::std::os::raw::c_void,
    pub cmdp: *mut ::std::os::raw::c_uchar,
    pub sbp: *mut ::std::os::raw::c_uchar,
    pub timeout: ::std::os::raw::c_uint,
    pub flags: ::std::os::raw::c_uint,
    pub pack_id: ::std::os::raw::c_int,
    pub usr_ptr: *mut ::std::os::raw::c_void,
    pub status: ::std::os::raw::c_uchar,
    pub masked_status: ::std::os::raw::c_uchar,
    pub msg_status: ::std::os::raw::c_uchar,
    pub sb_len_wr: ::std::os::raw::c_uchar,
    pub host_status: ::std::os::raw::c_ushort,
    pub driver_status: ::std::os::raw::c_ushort,
    pub resid: ::std::os::raw::c_int,
    pub duration: ::std::os::raw::c_uint,
    pub info: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sg_io_hdr"][::std::mem::size_of::<sg_io_hdr>() - 88usize];
    ["Alignment of sg_io_hdr"][::std::mem::align_of::<sg_io_hdr>() - 8usize];
    ["Offset of field: sg_io_hdr::interface_id"]
        [::std::mem::offset_of!(sg_io_hdr, interface_id) - 0usize];
    ["Offset of field: sg_io_hdr::dxfer_direction"]
        [::std::mem::offset_of!(sg_io_hdr, dxfer_direction) - 4usize];
    ["Offset of field: sg_io_hdr::cmd_len"][::std::mem::offset_of!(sg_io_hdr, cmd_len) - 8usize];
    ["Offset of field: sg_io_hdr::mx_sb_len"]
        [::std::mem::offset_of!(sg_io_hdr, mx_sb_len) - 9usize];
    ["Offset of field: sg_io_hdr::iovec_count"]
        [::std::mem::offset_of!(sg_io_hdr, iovec_count) - 10usize];
    ["Offset of field: sg_io_hdr::dxfer_len"]
        [::std::mem::offset_of!(sg_io_hdr, dxfer_len) - 12usize];
    ["Offset of field: sg_io_hdr::dxferp"][::std::mem::offset_of!(sg_io_hdr, dxferp) - 16usize];
    ["Offset of field: sg_io_hdr::cmdp"][::std::mem::offset_of!(sg_io_hdr, cmdp) - 24usize];
    ["Offset of field: sg_io_hdr::sbp"][::std::mem::offset_of!(sg_io_hdr, sbp) - 32usize];
    ["Offset of field: sg_io_hdr::timeout"][::std::mem::offset_of!(sg_io_hdr, timeout) - 40usize];
    ["Offset of field: sg_io_hdr::flags"][::std::mem::offset_of!(sg_io_hdr, flags) - 44usize];
    ["Offset of field: sg_io_hdr::pack_id"][::std::mem::offset_of!(sg_io_hdr, pack_id) - 48usize];
    ["Offset of field: sg_io_hdr::usr_ptr"][::std::mem::offset_of!(sg_io_hdr, usr_ptr) - 56usize];
    ["Offset of field: sg_io_hdr::status"][::std::mem::offset_of!(sg_io_hdr, status) - 64usize];
    ["Offset of field: sg_io_hdr::masked_status"]
        [::std::mem::offset_of!(sg_io_hdr, masked_status) - 65usize];
    ["Offset of field: sg_io_hdr::msg_status"]
        [::std::mem::offset_of!(sg_io_hdr, msg_status) - 66usize];
    ["Offset of field: sg_io_hdr::sb_len_wr"]
        [::std::mem::offset_of!(sg_io_hdr, sb_len_wr) - 67usize];
    ["Offset of field: sg_io_hdr::host_status"]
        [::std::mem::offset_of!(sg_io_hdr, host_status) - 68usize];
    ["Offset of field: sg_io_hdr::driver_status"]
        [::std::mem::offset_of!(sg_io_hdr, driver_status) - 70usize];
    ["Offset of field: sg_io_hdr::resid"][::std::mem::offset_of!(sg_io_hdr, resid) - 72usize];
    ["Offset of field: sg_io_hdr::duration"][::std::mem::offset_of!(sg_io_hdr, duration) - 76usize];
    ["Offset of field: sg_io_hdr::info"][::std::mem::offset_of!(sg_io_hdr, info) - 80usize];
};
pub type sg_io_hdr_t = sg_io_hdr;
