//! Transport-agnostic implementations of the wire protocol of the various scanners

pub mod caps;
pub mod cdbs;
pub mod mode;
pub mod sense;
pub mod session;
pub mod window;

// nkscan/
//   Cargo.toml            cli / python features, two bins — as-is
//   docs/                 the two specs + PROTOCOL.md
//   nkscan.pyi            generated by stub_gen; the contract negpy consumes
//   src/
//     lib.rs              pub mod transport, protocol, device, scan, error
//     error.rs            the public taxonomy the .pyi already names
//     transport/          ✅ wire framing only
//     protocol/
//       caps/             {mod,identity,address,setwindow,other,errata}.rs
//       cdb.rs            the 17 builders
//       sense.rs          interpret(&Sense) -> Outcome
//       session.rs        state + the retry loop + low-level methods
//       window.rs         50-byte descriptor codec
//       focus.rs          impl Session — AF/AE sequences
//       decode.rs         (caps, window) -> Layout
//     device.rs           discovery across all three transports
//     scan/
//       mod.rs            Job + impl Session::scan
//       result.rs         ScanResult: linear u16 + metadata
//     python.rs           #[cfg(feature = "python")]
//     bin/
//       nkscan/           #[cfg(feature = "cli")]
//       stub_gen.rs
