name: Release

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write
    packages: write

jobs:
    build-linux:
        name: Build Linux artifacts
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@v13

            - name: Setup Nix cache
              uses: DeterminateSystems/magic-nix-cache-action@v7

            - name: Build x86_64 binary
              run: |
                  nix build --print-build-logs
                  cp result/bin/nkscan nkscan-x86_64-unknown-linux-gnu

            - name: Upload Linux binaries to release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      nkscan-x86_64-unknown-linux-gnu

    build-windows:
        name: Build Windows artifact
        runs-on: windows-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Rust
              uses: dtolnay/rust-toolchain@master
              with:
                  toolchain: "1.96"

            - name: Cache Rust artifacts
              uses: Swatinem/rust-cache@v2

            - name: Build Windows binary
              run: |
                  cargo build --release -p nkscan --features=cli
                  cp target/release/nkscan.exe nkscan-x86_64-pc-windows-msvc.exe

            - name: Upload Windows binary to release
              uses: softprops/action-gh-release@v2
              with:
                  files: nkscan-x86_64-pc-windows-msvc.exe
